---
- name: "Set up a Matrix server"
  hosts: "{{ target if target is defined else 'matrix_servers' }}"
  become: true

  vars:
    # https://stackoverflow.com/a/41595937
    local_user: "{{ lookup('env', 'USER') }}"

  roles:
    - dotfiles
    - matrix-base
    - matrix-mailer
    - matrix-postgres
    - matrix-corporal
    - matrix-bridge-appservice-discord
    - matrix-bridge-appservice-slack
    - matrix-bridge-appservice-webhooks
    - matrix-bridge-appservice-irc
    - matrix-bridge-mautrix-facebook
    - matrix-bridge-mautrix-hangouts
    - matrix-bridge-mautrix-telegram
    - matrix-bridge-mautrix-whatsapp
    - matrix-bridge-mx-puppet-discord
    - matrix-bridge-mx-puppet-steam
    - matrix-bridge-mx-puppet-skype
    - matrix-bridge-mx-puppet-slack
    - matrix-bridge-mx-puppet-twitter
    - matrix-bridge-mx-puppet-instagram
    - matrix-bridge-sms
    - matrix-bot-matrix-reminder-bot
    - matrix-synapse
    - matrix-synapse-admin
    - matrix-client-element
    - matrix-jitsi
    - matrix-ma1sd
    - matrix-dimension
    - matrix-email2matrix
    - matrix-nginx-proxy
    - matrix-coturn
    - matrix-common-after

  post_tasks:
    # record the state (commit tag) of this playbook at time of last run
    - name: Record the current commit tag of this playbook to logfile
      local_action: shell git log --pretty="Playbook last committed by %cn on %cd (%H)" -1 >> playbook.log
      args:
        chdir: "{{ playbook_dir }}"
      become: true
      become_user: "{{ local_user }}"
      tags: always

