#!/bin/bash

# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
# Reset
Color_Off='\033[0m'       # Text Reset
# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White
# Underline
UBlack='\033[4;30m'       # Black
URed='\033[4;31m'         # Red
UGreen='\033[4;32m'       # Green
UYellow='\033[4;33m'      # Yellow
UBlue='\033[4;34m'        # Blue
UPurple='\033[4;35m'      # Purple
UCyan='\033[4;36m'        # Cyan
UWhite='\033[4;37m'       # White
# Background
On_Black='\033[40m'       # Black
On_Red='\033[41m'         # Red
On_Green='\033[42m'       # Green
On_Yellow='\033[43m'      # Yellow
On_Blue='\033[44m'        # Blue
On_Purple='\033[45m'      # Purple
On_Cyan='\033[46m'        # Cyan
On_White='\033[47m'       # White
# High Intensity
IBlack='\033[0;90m'       # Black
IRed='\033[0;91m'         # Red
IGreen='\033[0;92m'       # Green
IYellow='\033[0;93m'      # Yellow
IBlue='\033[0;94m'        # Blue
IPurple='\033[0;95m'      # Purple
ICyan='\033[0;96m'        # Cyan
IWhite='\033[0;97m'       # White
# Bold High Intensity
BIBlack='\033[1;90m'      # Black
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
BIWhite='\033[1;97m'      # White
# High Intensity backgrounds
On_IBlack='\033[0;100m'   # Black
On_IRed='\033[0;101m'     # Red
On_IGreen='\033[0;102m'   # Green
On_IYellow='\033[0;103m'  # Yellow
On_IBlue='\033[0;104m'    # Blue
On_IPurple='\033[0;105m'  # Purple
On_ICyan='\033[0;106m'    # Cyan
On_IWhite='\033[0;107m'   # White


# clear the screen
clear
# http://www.patorjk.com/software/taag/#p=display&f=Slant&t=oran
cat << "EOF"
  ____  _________ _____ 
 / __ \/ ___/ __ `/ __ \
/ /_/ / /  / /_/ / / / /
\____/_/   \__,_/_/ /_/ 
                       
EOF

ipv4address=$(ip addr show eth0 | grep 'inet ' | awk '{print $2}')
# uptime in pretty format without the initial 'up ' in the output
uptimestring=$(uptime -p | cut -d' ' -f2-)

echo "This server is running $(lsb_release -is) $(lsb_release -rs) ($(uname -o) $(uname -r) $(uname -m))"
printf "IPv4 address: ${BWhite}$ipv4address${Color_Off}\t ${On_Red}Helsinki${Color_Off} (Hetzner)\n"
printf "Uptime: ${BPurple}$uptimestring${Color_Off}\n"

printf "\nServices hosted on this VPS:\n"

printf "  * Web directory:\n"

printf "    * matrix.chepec.se      -- Matrix server\n"
printf "    * jitsi.chepec.se       -- Jitsi video conferencing\n"
printf "    * element.chepec.se     -- Element (Matrix client)\n"

dockerv=$(docker -v | awk '{print $3}')
dockerversion=${dockerv::-1} # removes the last character (which is a comma)
# Python up to v3.3 outputs the version to stderr, so we have to redirect to capture the output # https://stackoverflow.com/a/50735197
py2version=$(python --version 2>&1 | awk '{print $2}')
py3version=$(python3 --version | awk '{print $2}')
opensshv=$(dpkg -l | awk '/openssh-server/{print $3}')
# removes the prepended "1:" string in front of the actual version string
opensshversion=${opensshv#"1:"}

printf "  * Software and services:\n"
printf "    * Docker\t $dockerversion\n"
printf "    * Python\t $py3version; $py2version\n"
printf "    * ${BWhite}OpenSSH${Color_Off}\t $opensshversion\n"

printf "\n"
printf "  **** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ****\n"
printf "  *** The services on this host are managed by Ansible playbook ***\n"
printf "  *** github.com/chepec/matrix-docker                           ***\n"
printf "  *** NOTE: they are completely Dockerised                      ***\n"
printf "  **** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ****\n"

printf "\nThis file was last modified on $(date -r $0 -R)\n"

exit 0
