# The bare domain name which represents your Matrix identity.
# Matrix user ids for your server will be of the form (`@user:<matrix-domain>`).
matrix_domain: "{{ matrix_host.domain }}"
matrix_coturn_turn_external_ip_address: "{{ matrix_host.ipv4 }}"

# This is something which is provided to Let's Encrypt when retrieving SSL certificates for domains.
# In case SSL renewal fails at some point, you'll also get an email notification there. If you decide to use another method for managing SSL certifites (different than the default Let's Encrypt), you won't be required to define this variable (see `docs/configuring-playbook-ssl-certificates.md`).
matrix_ssl_lets_encrypt_support_email: "{{ email_webmaster }}"

# I've configured /.well-known as a Redirect (from chepec.se -> matrix.chepec.se)
# instead of a ProxyPass (for reasons), so we need to tell this playbook to follow redirects
# https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/101
matrix_nginx_proxy_self_check_well_known_matrix_client_follow_redirects: safe

# Synapse Admin
# You need to create one admin user *before* you can use Synapse Admin
matrix_synapse_admin_enabled: true


### Bridging other networks
matrix_bot_matrix_reminder_bot_enabled: false
matrix_appservice_discord_enabled: false
matrix_appservice_irc_enabled: false
matrix_appservice_slack_enabled: false
matrix_appservice_webhooks_enabled: false
matrix_mautrix_hangouts_enabled: false
matrix_mautrix_telegram_enabled: false
matrix_mx_puppet_discord_enabled: false
matrix_mx_puppet_instagram_enabled: false
matrix_mx_puppet_skype_enabled: false
matrix_mx_puppet_slack_enabled: false
matrix_mx_puppet_steam_enabled: false
matrix_mx_puppet_twitter_enabled: false
matrix_sms_bridge_enabled: false

# Matrix <--> Facebook Messenger
# https://github.com/tulir/mautrix-facebook/
matrix_mautrix_facebook_enabled: true

# Matrix <--> Whatsapp bridge
# https://github.com/tulir/mautrix-whatsapp
matrix_mautrix_whatsapp_enabled: true


### Jitsi
# https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-jitsi.md
matrix_jitsi_enabled: true
matrix_jitsi_enable_auth: true
matrix_jitsi_enable_guests: true


### Matrix Corporal policy
matrix_corporal_enabled: false
# https://github.com/devture/matrix-corporal
# https://github.com/devture/matrix-corporal/blob/master/docs/policy.md#user-policy-fields
# https://stackoverflow.com/questions/16918602/how-to-base64-encode-image-in-linux-bash-shell
# NOTE! It's not that simple. To use Corporal we must also configure Shared Secret Auth password provider module. See https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-matrix-corporal.md
matrix_corporal_configuration_extension_json: |
  {
    "schemaVersion": 1,

    "flags": {
      "allowCustomUserDisplayNames": true,
      "allowCustomUserAvatars": true
    },

    "users": [
      {
        "id": "@admin:{{ matrix_domain }}",
        "active": true,
        "authType": "bcrypt",
        "authCredential": "{{ admin_bcrypted_pwd }}",
        "displayName": "superadmin"
      },
      {
        "id": "@taha:{{ matrix_domain }}",
        "active": true,
        "authType": "bcrypt",
        "authCredential": "{{ taha_bcrypted_pwd }}",
        "displayName": "TA",
        "avatarUri": "{{ taha_avataruri }}"
      }
    ]
  }
